import { storeFetch as fetch } from './backend';
import {useState,useEffect,FormEvent} from 'react';
import {Search,Copy,MessageCircle,ArrowUpLeft,Plus,Package,ShieldCheck,MapPin,Phone,Check,Loader2,Pencil,Trash2,X} from 'lucide-react';
import {Select,SelectTrigger,SelectContent,SelectItem,SelectValue} from '@/components/ui/select';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Toaster,toast} from 'sonner';
import cats from '@/lib/categories.json';
type Product={id:string;name:string;category:string;price:number;quantity:number;description:string;image:string};
const words={ps:{brand:'اسحاقزاده آنلاین سټور',collection:'د جنسونو ټولګه',categories:'کټګورۍ',search:'د جنس نوم ولټوئ...',all:'ټول جنسونه',copy:'لینک کاپي کړه',share:'په واټساپ کې یې ولېږه',empty:'لا جنس نه دی ثبت شوی',emptyText:'ثبت شوي جنسونه به دلته ښکاره شي.',none:'جنس ونه موندل شو',retry:'بیا هڅه وکړئ',detail:'د جنس معلومات',price:'افغانۍ',stock:'پاتې شمېر',admin:'اډمین',close:'بندول',copied:'لینک کاپي شو',subtitle:'جنس وټاکئ، لینک یې شریک کړئ.',contact:'له موږ سره اړیکه',count:'جنسونه'},fa:{brand:'فروشگاه آنلاین اسحاقزاده',collection:'مجموعه محصولات',categories:'دسته‌بندی‌ها',search:'نام محصول را جستجو کنید...',all:'همه محصولات',copy:'کپی لینک',share:'ارسال در واتساپ',empty:'هنوز محصولی ثبت نشده',emptyText:'محصولات ثبت شده در اینجا نمایش داده می‌شوند.',none:'محصولی پیدا نشد',retry:'تلاش دوباره',detail:'جزئیات محصول',price:'افغانی',stock:'موجودی',admin:'مدیر',close:'بستن',copied:'لینک کپی شد',subtitle:'محصول را انتخاب و لینک آن را شریک کنید.',contact:'تماس با ما',count:'محصول'},en:{brand:'Ishaqzada Online Store',collection:'The collection',categories:'Categories',search:'Search for a product...',all:'All products',copy:'Copy product link',share:'Share on WhatsApp',empty:'No products added yet',emptyText:'Products will appear here once added.',none:'No products found',retry:'Try again',detail:'Product details',price:'AFN',stock:'Available quantity',admin:'Admin',close:'Close',copied:'Link copied',subtitle:'Find a product. Share its link.',contact:'Contact us',count:'products'}};
const catNames:{[key:string]:string[]}={'ټول':['همه','All'],'رنګ':['رنگ مو','Hair color'],'میکپ سامان':['لوازم آرایش','Makeup'],'وریښتان':['موی مصنوعی','Hair'],'شمپو':['شامپو','Shampoo'],'شمپو او تیل':['شامپو و روغن','Shampoo & oil'],'سپري':['اسپری','Spray'],'سیرم':['سرم','Serum'],'معجون':['معجون','Majoon'],'تیل':['روغن','Oil'],'کپسول':['کپسول','Capsules'],'کپسول او تیل':['کپسول و روغن','Capsules & oil'],'کریم او فیس واش':['کریم و شوینده صورت','Cream & cleanser'],'کریم':['کریم','Cream'],'فیس واش':['شوینده صورت','Face wash'],'ساعتونه':['ساعت‌ها','Watches'],'عطرونه':['عطرها','Perfumes'],'فوډر':['پودر','Powder'],'چائ':['چای','Tea'],'کریم او سیرم':['کریم و سرم','Cream & serum']};
export default function Store({admin=false}:{admin?:boolean}){
 const [lang,setLang]=useState<'ps'|'fa'|'en'>('ps');const t=words[lang];const catLabel=(n:string)=>lang==='ps'?n:catNames[n]?.[lang==='fa'?0:1]||n;
 const [products,setProducts]=useState<Product[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[category,setCategory]=useState('ټول'),[search,setSearch]=useState(''),[selected,setSelected]=useState<Product|null>(null),[editing,setEditing]=useState<Product|{}|null>(null),[deleting,setDeleting]=useState<Product|null>(null),[saving,setSaving]=useState(false),[formCategory,setFormCategory]=useState(cats[1].name),[copyFallback,setCopyFallback]=useState('');
 async function load(){setLoading(true);setError('');try{const r=await fetch('/api/products');const j=await r.json() as {error:string;products:Product[]};if(!r.ok)throw Error(j.error);setProducts(j.products);return j.products as Product[];}catch(e){setError(lang==='en'?'Products could not be loaded. Please try again.':lang==='fa'?'محصولات بارگیری نشد. دوباره تلاش کنید.':'جنسونه راونه رسېدل؛ بیا هڅه وکړئ.');return null;}finally{setLoading(false);}}
 useEffect(()=>{const l=localStorage.getItem('store-language');if(l==='ps'||l==='fa'||l==='en')setLang(l);load();},[]);
 useEffect(()=>{document.documentElement.dir=lang==='en'?'ltr':'rtl';document.documentElement.lang=lang;localStorage.setItem('store-language',lang);},[lang]);
 useEffect(()=>{function sync(){const id=new URLSearchParams(location.search).get('product');setSelected(products.find(p=>p.id===id)||null);}sync();window.addEventListener('popstate',sync);return()=>window.removeEventListener('popstate',sync);},[products]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const life=new AbortController();try{Promise.resolve(context.registerTool({name:'search_store_products',description:'Search the catalog and update the visible product results.',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input:unknown){const q=(input as {query?:unknown})?.query;if(typeof q!=='string'||q.length>150)throw Error('A query of up to 150 characters is required');setSearch(q);setCategory('ټول');return {products:products.filter(p=>p.name.toLowerCase().includes(q.toLowerCase())).map(p=>({id:p.id,name:p.name,price:p.price}))};}},{signal:life.signal})).catch(()=>{});}catch{}return()=>life.abort();},[products]);
 const link=(p:Product)=>new URL('./',location.href).href+'?product='+encodeURIComponent(p.id);
 function open(p:Product){setSelected(p);history.pushState(null,'',`?product=${encodeURIComponent(p.id)}`);}
 function close(){setSelected(null);history.pushState(null,'',location.pathname);}
 async function copy(p:Product){const u=link(p);try{await navigator.clipboard.writeText(u);toast.success(t.copied);}catch{setCopyFallback(u);}}
 function share(p:Product){window.open('https://wa.me/?text='+encodeURIComponent(p.name+' — '+p.price+' AFN\n'+link(p)),'_blank','noopener,noreferrer');}
 function edit(p?:Product){setFormCategory(p?.category||cats[1].name);setEditing(p||{});}
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(saving)return;const data=new FormData(e.currentTarget);data.set('category',formCategory);if(editing&&'id'in editing)data.set('id',editing.id as string);setSaving(true);try{const r=await fetch('/api/products',{method:'POST',body:data});const j=await r.json() as {error:string;products:Product[]};if(!r.ok)throw Error(j.error);toast.success('جنس ثبت شو');setEditing(null);await load();}catch(e){toast.error((e as Error).message);}finally{setSaving(false);}}
 async function remove(){if(!deleting||saving)return;setSaving(true);try{const r=await fetch('/api/products',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:deleting.id})});const j=await r.json() as {error:string;products:Product[]};if(!r.ok)throw Error(j.error);setDeleting(null);toast.success('جنس حذف شو');await load();}catch(e){toast.error((e as Error).message);}finally{setSaving(false);}}
 const visible=products.filter(p=>(category==='ټول'||p.category===category)&&p.name.toLowerCase().includes(search.toLowerCase()));const ep=editing as Product|null;
 const shareButtons=(p:Product)=><div className="share-buttons"><button className="copy-btn" onClick={()=>copy(p)}><Copy size={17}/>{t.copy}</button><button className="whatsapp-btn" onClick={()=>share(p)}><MessageCircle size={18}/>{t.share}</button></div>;
 return <><Toaster position="top-center" richColors/><div className="topline"><span>ISHAQZADA FASHION COMPANY</span><a href="https://wa.me/93700426319" target="_blank" rel="noreferrer"><Phone size={13}/> 0700 426 319</a></div><header className="header"><a className="brand" href="./"><img src="./logo.jpg" alt="Ishaqzada"/><div><strong>{t.brand}</strong><small>ISHAQZADA · ONLINE STORE</small></div></a><div className="header-actions"><Select value={lang} onValueChange={v=>setLang(v as typeof lang)}><SelectTrigger aria-label="Language"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="ps">پښتو</SelectItem><SelectItem value="fa">دری</SelectItem><SelectItem value="en">English</SelectItem></SelectContent></Select><a className="admin-link" href={admin?'./':'?admin=1'}><ShieldCheck size={19}/><span>{admin?'سټور':t.admin}</span></a>{admin&&<button className="admin-link" onClick={()=>{localStorage.removeItem('store-session');location.href='./';}}>وتل</button>}</div></header>
 <main className="shell"><section className="intro"><div><span className="eyebrow">ISHAQZADA COLLECTION</span><h1>{admin?'د جنسونو اداره':t.collection}<span className="gold-dot">.</span></h1><p>{admin?'نوی جنس ثبت کړئ یا د ثبت شویو جنسونو معلومات اصلاح کړئ.':t.subtitle}</p></div>{admin?<button className="primary" onClick={()=>edit()}><Plus size={19}/>نوی جنس ثبت کړه</button>:<div className="intro-mark"><Package size={30}/><span>ISHAQZADA<br/><b>STORE</b></span></div>}</section>
 <div className="catalog-layout"><aside className="categories"><div className="section-title"><h2>{t.categories}</h2><span>{cats.length-1}</span></div><div className="category-grid">{cats.map(c=><button key={c.name} className={'category '+(category===c.name?'active':'')} onClick={()=>setCategory(c.name)} aria-pressed={category===c.name}><img src={'.'+c.image} alt="" loading="lazy"/><span>{catLabel(c.name)}</span>{category===c.name&&<Check className="cat-check" size={15}/>}</button>)}</div></aside><section className="products-section"><div className="search-wrap"><Search size={20}/><input aria-label={t.search} placeholder={t.search} value={search} onChange={e=>setSearch(e.target.value)}/>{search&&<button aria-label={t.close} onClick={()=>setSearch('')}><X size={18}/></button>}</div><div className="results-heading"><h2>{category==='ټول'?t.all:catLabel(category)}</h2><span>{visible.length} {t.count}</span></div>
 {loading?<div className="state"><Loader2 className="spin"/><p>{lang==='en'?'Loading…':'جنسونه راځي…'}</p></div>:error?<div className="state"><Package size={36}/><h3>{error}</h3><button className="primary" onClick={load}>{t.retry}</button></div>:visible.length?<div className="products">{visible.map(p=><article className="product" key={p.id}><button className="product-photo" onClick={()=>open(p)}><img src={p.image} alt={p.name} loading="lazy"/><span className="view-icon"><ArrowUpLeft size={20}/></span></button><div className="product-body"><small>{catLabel(p.category)}</small><button className="product-title" onClick={()=>open(p)}>{p.name}</button><div className="price-row"><strong>{p.price.toLocaleString()} <small>{t.price}</small></strong><span>{t.stock}: {p.quantity}</span></div>{shareButtons(p)}{admin&&<div className="edit-buttons"><button onClick={()=>edit(p)}><Pencil size={16}/>اصلاح</button><button onClick={()=>setDeleting(p)}><Trash2 size={16}/>حذف</button></div>}</div></article>)}</div>:<div className="state empty"><div className="empty-icon"><Package size={40}/></div><h3>{products.length?t.none:t.empty}</h3><p>{products.length?'':t.emptyText}</p>{admin&&<button className="primary" onClick={()=>edit()}><Plus size={18}/>لومړی جنس ثبت کړه</button>}</div>}
 </section></div></main><footer><div className="footer-brand"><img src="./logo.jpg" alt=""/><div><strong>{t.brand}</strong><p>کندهار، د شهیدانو چوک، عمري تجارتي مارکیټ</p></div></div><a href="https://wa.me/93700426319" target="_blank" rel="noreferrer"><MessageCircle size={21}/><span>{t.contact}<b dir="ltr">0700 426 319</b></span><ArrowUpLeft size={20}/></a></footer>
 <Dialog open={!!selected} onOpenChange={v=>{if(!v)close();}}><DialogContent className="product-dialog"><DialogTitle>{selected?.name||t.detail}</DialogTitle><DialogDescription>{selected?catLabel(selected.category):t.detail}</DialogDescription>{selected&&<><img className="detail-photo" src={selected.image} alt={selected.name}/><div className="price-row"><strong>{selected.price.toLocaleString()} {t.price}</strong><span>{t.stock}: {selected.quantity}</span></div><p className="description">{selected.description}</p>{shareButtons(selected)}</>}</DialogContent></Dialog>
 <Dialog open={!!copyFallback} onOpenChange={v=>{if(!v)setCopyFallback('');}}><DialogContent><DialogTitle>{t.copy}</DialogTitle><DialogDescription>{lang==='en'?'Select and copy this link:':'لینک وټاکئ او کاپي یې کړئ:'}</DialogDescription><input dir="ltr" className="field" value={copyFallback} readOnly onFocus={e=>e.target.select()}/></DialogContent></Dialog>
 {admin&&<><Dialog open={editing!==null} onOpenChange={v=>{if(!v&&!saving)setEditing(null);}}><DialogContent className="edit-dialog"><DialogTitle>{ep?.id?'د جنس اصلاح':'نوی جنس ثبت کړه'}</DialogTitle><DialogDescription>نوم، قیمت، کټګوري او عکس ولیکئ.</DialogDescription><form onSubmit={save} className="edit-form"><label>د جنس نوم<input name="name" defaultValue={ep?.name} maxLength={150} required/></label><label>کټګوري<Select value={formCategory} onValueChange={setFormCategory}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{cats.slice(1).map(c=><SelectItem key={c.name} value={c.name}>{c.name}</SelectItem>)}</SelectContent></Select></label><div className="form-row"><label>قیمت — افغانۍ<input name="price" type="number" min="0" step="0.01" defaultValue={ep?.price} required/></label><label>پاتې شمېر<input name="quantity" type="number" min="0" step="1" defaultValue={ep?.quantity??0} required/></label></div><label>تشریحات<textarea name="description" defaultValue={ep?.description} maxLength={4000} rows={4}/></label><label>عکس<input type="file" name="photo" accept="image/jpeg,image/png,image/webp" required={!ep?.id}/><small>JPG / PNG / WebP · تر ۶ MB پورې</small></label><button className="primary" type="submit" disabled={saving}>{saving?<Loader2 className="spin"/>:<Check size={18}/>}ثبت کړه</button></form></DialogContent></Dialog><AlertDialog open={!!deleting} onOpenChange={v=>{if(!v&&!saving)setDeleting(null);}}><AlertDialogContent><AlertDialogTitle>دا جنس حذف شي؟</AlertDialogTitle><AlertDialogDescription>{deleting?.name} به له سټور څخه لرې شي.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel disabled={saving}>نه</AlertDialogCancel><AlertDialogAction disabled={saving} onClick={e=>{e.preventDefault();remove();}}>هو، حذف کړه</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></>}
 </>;
}
